wandb_version: 1

dataset_path:
  desc: null
  value: ./data/wrench_data
dataset_name:
  desc: null
  value: imdb
feature_extractor:
  desc: null
  value: bert
stop_words:
  desc: null
  value: null
stemming:
  desc: null
  value: porter
append_cdr:
  desc: null
  value: false
sampler:
  desc: null
  value: passive
embedding_model:
  desc: null
  value: all-MiniLM-L12-v2
distance:
  desc: null
  value: cosine
uncertain_metric:
  desc: null
  value: entropy
neighbor_num:
  desc: null
  value: 10
alpha:
  desc: null
  value: 1.0
beta:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 1.0
label_model:
  desc: null
  value: Snorkel
use_soft_labels:
  desc: null
  value: false
end_model:
  desc: null
  value: logistic
default_class:
  desc: null
  value: null
tune_label_model:
  desc: null
  value: true
tune_end_model:
  desc: null
  value: true
tune_metric:
  desc: null
  value: acc
lf_agent:
  desc: null
  value: chatgpt
lf_type:
  desc: null
  value: keyword
lf_filter:
  desc: null
  value:
  - acc
  - overlap
lf_acc_threshold:
  desc: null
  value: 0.6
lf_overlap_threshold:
  desc: null
  value: 0.95
max_lf_per_iter:
  desc: null
  value: 100
max_ngram:
  desc: null
  value: 3
lf_llm_model:
  desc: null
  value: gpt-3.5-turbo
example_per_class:
  desc: null
  value: 1
return_explanation:
  desc: null
  value: false
example_selection:
  desc: null
  value: random
temperature:
  desc: null
  value: 0.7
top_p:
  desc: null
  value: 1
n_completion:
  desc: null
  value: 1
num_query:
  desc: null
  value: 3
train_iter:
  desc: null
  value: 1
sleep_time:
  desc: null
  value: 30.0
early_stop:
  desc: null
  value: false
runs:
  desc: null
  value: 5
seed:
  desc: null
  value: 42
display:
  desc: null
  value: false
save_wandb:
  desc: null
  value: true
method:
  desc: null
  value: LLMDP
group_id:
  desc: null
  value: upb6fbqc
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704853941.138801
    t:
      1:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 49
      - 53
      - 55
      - 75
      - 95
      2:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 49
      - 53
      - 55
      - 75
      - 95
      3:
      - 2
      - 16
      - 23
      4: 3.9.0
      5: 0.16.2
      6: 4.36.2
      8:
      - 5
      13: darwin-x86_64
